添加 机器之心SOTA！模型
LinuxSuRen/remote-jobs-in-china pull request #29
Opened 2022-05-24 16:53 UTC by chainn

如题

2022-05-25 06:18 UTC, LinuxSuRen requested changes
感谢提供线索，方便的话，帮忙提供下能体现支持 remote 工作的链接、截图等。谢谢合作。

另外，不好意思，为了避免大家修改同一个 README 文件导致的冲突，现在把每个公司的信息都放到 items 目录下的 YAML 文件了。还得麻烦你重新修改下了。

2022-06-01 10:00 UTC, chainn commented
公司Boss直聘主页已添加（审核通过后可见）

2022-06-01 11:25 UTC, LinuxSuRen commented
非常感谢 @chainn ，我翻了几个，没有找到远程或者remote字样，要是您那边方便的话，帮忙贴个截图，谢谢。

2022-06-28 11:50 UTC, LinuxSuRen commented
没有反馈的话，本周就关闭该 PR 了哈

2022-07-01 01:04 UTC, closed without merging